version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.test
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=sample"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data: