services:
  api-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.test
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-dev:5432/postgres?schema=sample"
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
    depends_on:
      - postgres-dev 
  postgres-dev:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
  redis-dev:
    image: redis:latest
    ports:
      - "6377:6379"
    volumes:
      - redis-dev-data:/data
volumes:
  postgres-dev-data:
  redis-dev-data: