
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=sample"
    volumes:
      - .:/home/app
    depends_on:
    - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data: