
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=sample"
    volumes:
      - .:/home/app
    depends_on:
    - postgres
    - redis

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
volumes:
  postgresql_data:
  redis_data: 