version: '3.8'

services:
  database:
    container_name: fastfeet
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastfeet
